import React from 'react';
import { useNavigate } from 'react-router-dom';

// Import semua aset kamu di sini
// Pastikan ekstensi filenya sesuai ya (png, jpg, atau gif)
// @ts-ignore
import rovModel from '../assets/rov-model.png';
// @ts-ignore
import exploreGif from '../assets/Logo XploreRobot.gif'; 
// @ts-ignore
import bgBanner from '../assets/rov-latar.png';
// @ts-ignore
import bgTeam from '../assets/rov-bg.jpg'; 

const menus = [
  { path: '/simulation', title: 'Firmware Autopilot',  desc: 'Update flight controller firmware.', icon: '🚀' },
  { path: '/params',     title: 'Autopilot Parameters',desc: 'Modify vehicle parameters in real-time.', icon: '📑' },
  { path: '/live',       title: 'Live Telemetry',      desc: 'Real-time sensor data and video stream.', icon: '📊' },
  { path: '/Mission',    title: 'Mission Control',     desc: 'Create, manage, and execute navigation missions with real-time updates.', icon: '🎯' },
  { path: '/setup',      title: 'Vehicle Setup',       desc: 'Sensor calibrations and motor tests.',    icon: '⚙️' },
  { path: '/browser',    title: 'Log Browser',         desc: 'Allow browsing the Telemetry (.tlog) and Binary (.bin) logs generated by your vehicle.', icon: '📁' },
  { path: '/ping',       title: 'Ping Sonar Devices',  desc: 'Manage detected Ping family sonar devices, connected to either your Onboard Computer or its local network.', icon: '📡' },
  { path: '/video',      title: 'Video Streams',       desc: 'Manage your video devices and video streams.', icon: '🎥' },
  { path: '/kami',       title: 'Dokumentasi Team',    desc: 'Informasi tim kami.', icon: '👥' },
];

export const Home: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="space-y-6 animate-in fade-in duration-500 w-full">
      
      {/* =========================================
          1. HERO BANNER SECTION (rov-latar.png)
          ========================================= */}
      <div className="group relative flex flex-col md:flex-row bg-[#111c38] rounded-2xl overflow-hidden shadow-lg border border-slate-700/50 h-[220px]">
        {/* Background Banner */}
        <div 
          className="absolute inset-0 bg-cover bg-center opacity-50 mix-blend-overlay"
          style={{ backgroundImage: `url(${bgBanner})` }}
        ></div>

        {/* Bagian Teks (Kiri) */}
        <div className="relative w-full md:w-1/2 p-8 flex flex-col justify-center z-10">
          <h1 className="text-3xl md:text-5xl font-black text-white leading-tight mb-2 tracking-wide">
            EXPLOR ROBOT <br /> GROUND STATION
          </h1>
          <h2 className="text-sm md:text-base font-semibold text-blue-200 tracking-widest uppercase">
            Initialize System & Telemetry Control
          </h2>
        </div>

        {/* Bagian Interaktif (Kanan) */}
        <div className="relative w-full md:w-1/2 flex items-center justify-center overflow-hidden z-10 hidden md:flex">
          
          {/* 1. GIF Tim di belakang */}
          <img 
            src={exploreGif} 
            alt="Explore Team" 
            // 👇 Ubah w-40 menjadi w-56 (atau w-60 kalau masih kurang gede)
            className="absolute w-56 h-auto z-10 invisible group-hover:visible group-hover:opacity-100 transition-opacity duration-500 delay-150 invert drop-shadow-lg"
          />
          
          {/* 2. Gambar ROV yang geser */}
          <img 
            src={rovModel} 
            alt="ROV" 
            className="absolute w-64 h-auto z-20 transform transition-transform duration-700 ease-in-out group-hover:translate-x-40"
          />
          
        </div>
      </div>

      {/* =========================================
          2. GRID CARDS SECTION
          ========================================= */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
        {menus.map((m) => {
          const isTeamCard = m.path === '/kami';

          return (
            <div 
              key={m.path} 
              onClick={() => navigate(m.path)}
              className={`relative rounded-xl p-4 flex flex-col justify-between border border-slate-700/50 hover:border-blue-500 hover:shadow-[0_0_15px_rgba(59,130,246,0.3)] transition-all cursor-pointer min-h-[140px] overflow-hidden group ${
                isTeamCard ? 'bg-transparent' : 'bg-[#1e293b]/90 backdrop-blur-sm hover:bg-[#253347]'
              }`}
            >
              {/* Latar Belakang Khusus untuk Dokumentasi Team */}
              {isTeamCard && (
                <>
                  <div 
                    className="absolute inset-0 bg-cover bg-center opacity-40 mix-blend-luminosity group-hover:mix-blend-normal transition-all duration-500"
                    style={{ backgroundImage: `url(${bgTeam})` }}
                  ></div>
                  <div className="absolute inset-0 bg-gradient-to-t from-[#0f172a] via-[#0f172a]/80 to-transparent"></div>
                </>
              )}

              {/* Konten Card Atas */}
              <div className="relative z-10">
                <span className={`text-[10px] uppercase tracking-wider ${isTeamCard ? 'text-slate-300 drop-shadow-md' : 'text-slate-400'}`}>
                  Pratinjau Koneksi
                </span>
                <div className="flex items-center gap-2 mt-1 mb-2">
                  <span className="text-blue-400">{m.icon}</span> 
                  <h3 className={`font-bold text-sm ${isTeamCard ? 'text-white drop-shadow-md' : 'text-white'}`}>
                    {m.title}
                  </h3>
                </div>
                <p className={`text-[11px] leading-tight ${isTeamCard ? 'text-slate-200 drop-shadow-md' : 'text-slate-400'}`}>
                  {m.desc}
                </p>
              </div>

              {/* Konten Card Bawah (Status) */}
              <div className="relative z-10 flex items-center gap-2 mt-4">
                <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse shadow-[0_0_8px_#10b981]"></div>
                <span className="text-[11px] font-medium text-slate-300">
                  Ready to Connect
                </span>
              </div>
            </div>
          );
        })}
      </div>

    </div>
  );
};

export default Home;